version: '3.8'

services:
  db:
    image: mysql:8
    container_name: charactern_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: characternections
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/characternnectionsbackend
    container_name: charactern_backend
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/characternections
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./frontend
    container_name: charactern_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: