spring.application.name=characternnectionsbackend
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/characternections
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
